"""Create sheets and tasks models

Revision ID: 8b7e8f733d05
Revises:
Create Date: 2024-01-30 18:21:22.897806

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8b7e8f733d05"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sheets",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=60), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_sheets_name"), "sheets", ["name"], unique=True)
    op.create_table(
        "tasks",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column(
            "status",
            postgresql.ENUM("IN_PROGRESS", "DONE", name="taskstatus"),
            nullable=False,
        ),
        sa.Column("sheet_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["sheet_id"], ["sheets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "sheet_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_index(op.f("ix_sheets_name"), table_name="sheets")
    op.drop_table("sheets")
    # ### end Alembic commands ###
