"""Create sheets and tasks tables

Revision ID: bc98873aa3b4
Revises:
Create Date: 2024-02-13 10:34:24.555760

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "bc98873aa3b4"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _get_task_status():
    return postgresql.ENUM("in_progress", "done", name="task_status")


def upgrade() -> None:
    task_status = _get_task_status()

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sheets",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=60), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("name", sa.String(length=20), nullable=False),
        sa.Column("description", sa.String(length=100), nullable=True),
        sa.Column("status", task_status, server_default="in_progress", nullable=False),
        sa.Column("sheet_id", sa.Integer(), nullable=False),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["sheet_id"], ["sheets.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "sheet_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tasks")
    op.drop_table("sheets")
    # ### end Alembic commands ###
    _get_task_status().drop(op.get_bind())
